version: "3"

services:

    shopware:
      image: dockware/dev:latest
      container_name: shopware
      ports:
         - "80:80"
      networks:
         - web
      volumes:
         - .:/var/www/html/custom/plugins/WerklOpenBlogware

    db:
      image: mysql:8.4
      container_name: mysql
      networks:
        - web
      environment:
        - MYSQL_ROOT_PASSWORD=hidden
        - MYSQL_USER=shopuser
        - MYSQL_PASSWORD=secret
        - MYSQL_DATABASE=shopware

networks:
  web:
    external: false

# DATABASE_URL=mysql://shopuser:secret@db:3306/shopware
# bin/console system:install --basic-setup --force
# bin/console plugin:install WerklOpenBlogware
